package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"apd/internal/document"
	"apd/internal/templates"
)

// FileExporter writes Markdown documents to a project-local output directory.
type FileExporter struct{ WorkingDir string }

// NewFileExporter returns a Markdown exporter rooted at the current project directory.
func NewFileExporter(workingDir string) FileExporter { return FileExporter{WorkingDir: workingDir} }

// Write renders and writes a Markdown document, returning the generated path.
func (e FileExporter) Write(doc document.Document, tmpl templates.Template) (string, error) {
	path := MarkdownPath(e.WorkingDir, doc)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", writeMarkdownError(path, err)
	}
	data := []byte(RenderMarkdown(doc, tmpl))
	tmp, err := os.CreateTemp(filepath.Dir(path), ".*.tmp")
	if err != nil {
		return "", writeMarkdownError(path, err)
	}
	tmpName := tmp.Name()
	defer os.Remove(tmpName)
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return "", writeMarkdownError(path, err)
	}
	if err := tmp.Close(); err != nil {
		return "", writeMarkdownError(path, err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return "", writeMarkdownError(path, err)
	}
	return path, nil
}

// MarkdownDir returns the project-local directory for generated Markdown files.
func MarkdownDir(workingDir string) string { return filepath.Join(workingDir, "apd-docs") }

// MarkdownPath returns the generated Markdown path for a document.
func MarkdownPath(workingDir string, doc document.Document) string {
	return filepath.Join(MarkdownDir(workingDir), doc.Metadata.SessionID+".md")
}

// RenderMarkdown renders a guided document as clean, manually editable Markdown.
func RenderMarkdown(doc document.Document, tmpl templates.Template) string {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# %s\n\n", doc.Metadata.Title)
	fmt.Fprintf(&b, "Generated by apd on %s.\n", doc.Metadata.UpdatedAt.UTC().Format("2006-01-02"))
	fmt.Fprintf(&b, "Template: %s v%d\n", doc.Template.ID, doc.Template.Version)
	fmt.Fprintf(&b, "Session: %s\n\n", doc.Metadata.SessionID)

	for _, section := range doc.Sections {
		if section.Status != document.StatusAnswered || strings.TrimSpace(section.Answer) == "" {
			continue
		}
		fmt.Fprintf(&b, "## %s\n\n%s\n\n", section.Title, strings.TrimRight(section.Answer, "\n"))
	}

	b.WriteString("## AI Context Pack\n\n")
	for _, item := range BuildContextPack(doc, tmpl).Items {
		fmt.Fprintf(&b, "### %s\n\n%s\n\n", item.Title, strings.TrimSpace(item.Content))
	}

	open := openSections(doc)
	if len(open) > 0 {
		b.WriteString("## Open / Skipped Sections\n\n")
		b.WriteString("| Section | Status |\n")
		b.WriteString("| --- | --- |\n")
		for _, section := range open {
			fmt.Fprintf(&b, "| %s | %s |\n", escapeTableCell(section.Title), displayStatus(section.Status))
		}
	}
	return b.String()
}

func openSections(doc document.Document) []document.SectionState {
	var open []document.SectionState
	for _, section := range doc.Sections {
		if section.Status == document.StatusSkipped || section.Status == document.StatusPending {
			open = append(open, section)
		}
	}
	return open
}

func displayStatus(status document.SectionStatus) string {
	switch status {
	case document.StatusSkipped:
		return "Skipped"
	case document.StatusPending:
		return "Pending"
	default:
		return string(status)
	}
}

func escapeTableCell(value string) string {
	return strings.ReplaceAll(value, "|", "\\|")
}

func writeMarkdownError(path string, err error) error {
	return fmt.Errorf("write markdown %q: %w; ensure the working directory is writable or run apd from the intended project directory", path, err)
}
